# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            GujjuCoders
tagline:          'Gujjus by heart, Indians by passion, BITSians by destiny.'
description:      'Gujjus by heart, Indians by passion, BITSians by destiny.'
url:              gujjucoders.me
baseurl:          /

author:
  name:           'Shyamal'
  url:            ''

gems:
  - jemoji
