# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            GujjuCoders
tagline:          'Gujjus by heart, Indians by passion, BITSians by destiny.'
description:      'Gujjus by heart, Indians by passion, BITSians by destiny.'
url:              http://svaderia.github.io
baseurl:          /GujjuCoders

author:
  name:           'Shyamal'
  url:            ''

gems:
                  [jekyll-paginate]
paginate:         5

